### ISSUE TITLE
Fire TV Cube - Crash on load

### ISSUE THREAD

**Issue by jonathanmasseurca** [mupen64plus-ae/mupen64plus-ae#927]
Hi,

I'm using Mupen 64 FZ 3.0.289

Since the last update of the Fire TV Cube (2nd generation) on Android 9 ( Fire OS 7.2.4.2 / PS7242/2216 ), I have this issue (All games crash on load, I also tried RetroArch with Mupen core and I have the same issue)

I also found some people with the same issue 
https://www.reddit.com/r/EmulationOnAndroid/comments/oxun1p/mupen64_plus_fz_picking_a_game_crash_the_app_back/

--------- beginning of main
[ 08-05 13:57:07.172 29909:29909 I/GalleryActivity ]: onResume

[ 08-05 13:57:07.193 29909:29979 I/OpenGLRenderer ]: Initialized EGL, version 1.4

[ 08-05 13:57:07.193 29909:29979 D/OpenGLRenderer ]: Swap behavior 2

[ 08-05 13:57:07.266 29909:29919 I/usae.v3.fzurit ]: Background concurrent copying GC freed 33173(2MB) AllocSpace objects, 2(104KB) LOS objects, 50% free, 8MB/17MB, paused 950us total 104.460ms

[ 08-05 13:57:07.268 29909:29979 D/mali_winsys ]: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000

[ 08-05 13:57:11.756 29909:29909 I/GalleryActivity ]: launchGameActivity

[ 08-05 13:57:11.824 29909:29909 I/GalleryActivity ]: onPause

[ 08-05 13:57:11.872  7553: 7553 E/mulationProces ]: Not starting debugger since process cannot load the jdwp agent.

[ 08-05 13:57:11.933 29909:29979 W/libEGL   ]: EGLNativeWindowType 0xdaf18808 disconnect failed

[ 08-05 13:57:11.933  7553: 7553 I/MultiDex ]: VM with version 2.1.0 has multidex support

[ 08-05 13:57:11.934  7553: 7553 I/MultiDex ]: Installing application

[ 08-05 13:57:11.934  7553: 7553 I/MultiDex ]: VM has multidex support, MultiDex support library is disabled.

[ 08-05 13:57:11.989  7553: 7553 D/AndroidRuntime ]: Shutting down VM

[ 08-05 13:57:11.995  7553: 7553 E/AndroidRuntime ]: FATAL EXCEPTION: main
Process: org.mupen64plusae.v3.fzurita:EmulationProcess, PID: 7553
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mupen64plusae.v3.fzurita/paulscode.android.mupen64plusae.game.GameActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2934)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3075)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.content.ContextWrapper.getResources(ContextWrapper.java:91)
	at android.view.ContextThemeWrapper.getResourcesInternal(ContextThemeWrapper.java:127)
	at android.view.ContextThemeWrapper.getResources(ContextThemeWrapper.java:121)
	at androidx.appcompat.app.AppCompatActivity.getResources(AppCompatActivity.java:577)
	at com.fireos.eve.EveContextCallback.init(EveContextCallback.java:27)
	at android.app.VendorContextCallback.callInit(VendorContextCallback.java:39)
	at android.app.ContextImpl.getSharedPreferencesCacheLocked(ContextImpl.java:468)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:430)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:423)
	at androidx.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:119)
	at paulscode.android.mupen64plusae.game.GameActivity.attachBaseContext(GameActivity.java:212)
	at android.app.Activity.attach(Activity.java:7064)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
	... 11 more

Thank you for your help,

**Comment by fzurita** [comment]
Yeah, this one will hard to debug since I don't have a fire TV.

Those errors tell me that some resource is missing from the OS that is needed to run the Game Activity. It's hard to tell what exactly from the crash dump.

**Comment by jonathanmasseurca** [comment]
Thanks you @fzurita for your quick reply,

I finally installed Android Studio and did the debug.

The null issue was caused by calling PreferenceManager.getDefaultSharedPreferences( newBase ); in the attachBaseContext.

I have replaced those lines 

From

`    @Override
    protected void attachBaseContext(Context newBase) {


        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences( newBase );

        // Locale
        String localeCode = preferences.getString( GlobalPrefs.KEY_LOCALE_OVERRIDE, DEFAULT_LOCALE_OVERRIDE );

        if(TextUtils.isEmpty(localeCode))
        {
            super.attachBaseContext(newBase);
        }
        else
        {
            super.attachBaseContext(LocaleContextWrapper.wrap(newBase,localeCode));
        }
    }`


To 

'
    @Override
    protected void attachBaseContext(Context newBase) {

        if(TextUtils.isEmpty(LocaleContextWrapper.getLocalCode()))
        {
            super.attachBaseContext(newBase);
        }
        else
        {
            super.attachBaseContext(LocaleContextWrapper.wrap(newBase,LocaleContextWrapper.getLocalCode()));
        }
    }
'

Now I can load and play all games using my Fire TV.

I'm not sure if this commit can cause other problem (I'm not an android dev), if you don't see any problem, you can commit the change in the merge request.


Best,

**Comment by jonathanmasseurca** [comment]
Resolved - Merge #930 - https://github.com/mupen64plus-ae/mupen64plus-ae/pull/930
